data=[
    {
        img:"../images/avi.svg",
        txt:"my-file.avi",
        p:"Admin",
        date:"20/06/2020",
        mega:"12.5MB",
    },
    {
        img:"../images/eps.svg",
        txt:"my-file.eps",
        p:"Uploader",
        date:"16/5/2021",
        mega:"207MB",
    },
    {
        img:"../images/psd.svg",
        txt:"my-file.psd",
        p:"Ahmed Tawfik",
        date:"20/06/2020",
        mega:"15.7MB",
    },
    {
        img:"../images/dll.svg",
        txt:"my-file.dll",
        p:"Coder",
        date:"06/04/2020",
        mega:"202MB",
    },
    {
        img:"../images/zip.svg",
        txt:"my-file.zip",
        p:"Download",
        date:"06/04/2020",
        mega:"209MB",
    },
    {
        img:"../images/psd.svg",
        txt:"my-file.psd",
        p:"Ahmed Tawfik",
        date:"20/06/2020",
        mega:"15.7MB",
    },
    {
        img:"../images/dll.svg",
        txt:"my-file.dll",
        p:"Coder",
        date:"06/04/2020",
        mega:"202MB",
    },
    {
        img:"../images/zip.svg",
        txt:"my-file.zip",
        p:"Download",
        date:"06/04/2020",
        mega:"209MB",
    },
    {
        img:"../images/eps.svg",
        txt:"my-file.eps",
        p:"Uploader",
        date:"16/5/2021",
        mega:"207MB",
    },
    {
        img:"../images/pdf.svg",
        txt:"my-file.pdf",
        p:"Elzero",
        date:"16/5/2021",
        mega:"5.5MB",
    },
    {
        img:"../images/avi.svg",
        txt:"my-file.avi",
        p:"Admin",
        date:"20/06/2020",
        mega:"12.5MB",
    },
    {
        img:"../images/eps.svg",
        txt:"my-file.eps",
        p:"Uploader",
        date:"16/5/2021",
        mega:"207MB",
    },
    {
        img:"../images/psd.svg",
        txt:"my-file.psd",
        p:"Ahmed Tawfik",
        date:"20/06/2020",
        mega:"15.7MB",
    },
    {
        img:"../images/dll.svg",
        txt:"my-file.dll",
        p:"Coder",
        date:"06/04/2020",
        mega:"202MB",
    },
    {
        img:"../images/psd.svg",
        txt:"my-file.psd",
        p:"Ahmed Tawfik",
        date:"20/06/2020",
        mega:"15.7MB",
    },
    {
        img:"../images/dll.svg",
        txt:"my-file.dll",
        p:"Coder",
        date:"06/04/2020",
        mega:"202MB",
    },
    {
        img:"../images/zip.svg",
        txt:"my-file.zip",
        p:"Download",
        date:"06/04/2020",
        mega:"209MB",
    },
    {
        img:"../images/eps.svg",
        txt:"my-file.eps",
        p:"Uploader",
        date:"16/5/2021",
        mega:"207MB",
    },
    {
        img:"../images/avi.svg",
        txt:"my-file.avi",
        p:"Admin",
        date:"20/06/2020",
        mega:"12.5MB",
    },
    {
        img:"../images/eps.svg",
        txt:"my-file.eps",
        p:"Uploader",
        date:"16/5/2021",
        mega:"207MB",
    },
    {
        img:"../images/psd.svg",
        txt:"my-file.psd",
        p:"Ahmed Tawfik",
        date:"20/06/2020",
        mega:"15.7MB",
    },
    {
        img:"../images/dll.svg",
        txt:"my-file.dll",
        p:"Coder",
        date:"06/04/2020",
        mega:"202MB",
    },
    {
        img:"../images/zip.svg",
        txt:"my-file.zip",
        p:"Download",
        date:"06/04/2020",
        mega:"209MB",
    },
]

let container=document.querySelector('.file-content');
let file=document.querySelector('.file');

data.forEach(e => {
    const clone=file.cloneNode(true);
    clone.querySelector('img').src=e.img;
    clone.querySelector('.name').textContent=e.txt;
    clone.querySelector('p').textContent=e.p;
    clone.querySelector('#date').textContent=e.date;
    clone.querySelector('#mega').textContent=e.mega;
    container.appendChild(clone);
});

